apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            - name: CALICO_IPV4POOL_CIDR
              value: "10.42.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "Never"
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=10.0.0.1"
            - name: FELIX_IPV6SUPPORT
              value: "false"
